### ISSUE TITLE
Task List #1

### ISSUE THREAD

**Issue by Diacod-I** [Diacod-I/ActivateFunk#1]
- [ ] - Add some more activation functions
- [ ] - Use an example point set to compare the outputs from all the activation functions.
- [ ] - Add some more content on the application aspect of each function
- [ ] - Keep track of the references
